### ISSUE TITLE
新しいアイコン

### ISSUE THREAD

**Issue by oame** [annict/annict#120]
Annictのロゴを見ている時にふと、回転させた'ア'と'A'は似てるなあと思いつき、よりAに近い造形でアイコンをデザインしてみました。enhancementなIssueを受け付けているのか不明ですが、作ってしまったものを捨ててしまうのも勿体無かったので登録しました。よろしくお願いします。

[.sketch / .png / .pdf形式のアイコンデータと提案PDFへのリンク](https://www.dropbox.com/sh/xo6lkxje9nj8jbg/AAC7LJQTVoxoBJXrW5sWIIufa?dl=0)

※文字部分のフォントは適当です。

![title](https://cloud.githubusercontent.com/assets/9673255/5203471/4a7e1dda-75ca-11e4-9b81-aad05378382a.png)
![overview](https://cloud.githubusercontent.com/assets/9673255/5203470/4a7afdb2-75ca-11e4-9220-77d33bcb0ea2.png)

**Comment by bojovs** [comment]
だいぶ時間が経ちましたが、ようやくサイト内に表示しているスクリーンショットを新しいロゴが入っているものに差し替えました! なのでこのIssueは閉じたいと思います。
新しいロゴ、僕の周りでも好評で、本当にありがたいです。また何かありましたら、お気軽にIssue投稿して頂ければと思います! m(__)m
