### ISSUE TITLE
作品のエピソード一覧の表示順序が話数の順序になっていない

### ISSUE THREAD

**Issue by kajisha** [annict/annict#1253]
## 発生した箇所

https://annict.jp/works/5002/episodes

![5226041011077120](https://user-images.githubusercontent.com/1960696/43366418-bcb518e8-9378-11e8-9bf5-1f1c5f6db864.png)

## 期待する動作

71話のあとに 72 話が表示されるとよさそうです。

**Comment by kajisha** [comment]
おそらく https://github.com/annict/annict/blob/master/app/controllers/episodes_controller.rb#L37 を話数でソートするよさそうでしょうか？
それならすぐに PR できそうなので、PR したいと思います。

**Comment by shimbaco** [comment]
![annict 2018-07-30 00-11-05](https://user-images.githubusercontent.com/56767/43367745-153c1246-938d-11e8-977f-43a33fdf32d0.png)

https://github.com/annict/annict/pull/1254 のデプロイ後、無事並び順がちゃんとした感じになりました 🎉 
https://annict.jp/works/5002/episodes

**Comment by kajisha** [comment]
ありがとうございますー :tada: :tada:
