### ISSUE TITLE
pc.css に多くの css が重複して出力されている

### ISSUE THREAD

**Issue by uu1t** [annict/annict#1859]
`pc-[hash].css` に多くの css が重複して出力されています。
例えば body 直下の `<div class="p-application ...">` のスタイルを見ると、`.flex-column` と `.d-flex` が重複しています。

<img width="529" alt="Screen Shot 2019-04-08 at 22 08 39" src="https://user-images.githubusercontent.com/35105763/55727266-94aeaa80-5a4c-11e9-8869-9812e3fcb7b9.png">

一方で `.p-application` は重複していません。 `app/frontend/packs/pc.js` 中で `pc.scss` と `db.scss` を読み込んでいるため、両方に共通する部分が重複して出力されているようです。

https://github.com/annict/annict/blob/6f30df09d6d784e4e7db82375abb52955ddd5179/app/frontend/packs/pc.js#L2-L3

**Comment by shimbaco** [comment]
修正してデプロイdoneです 🚀
