### ISSUE TITLE
GraphQLのwork_imageでattachmentの画像URLを参照したいです

### ISSUE THREAD

**Issue by chuross** [annict/annict#1909]
Annictのクライアントアプリを作っています。

アプリ内で表示する画像URLとして、
現状internal_urlとして扱われているattachmentも参照したいのですが、
こちらは今後公開される予定はありますでしょうか？

https://github.com/annict/annict/blob/master/app/graphql/types/objects/work_image_type.rb#L30

**Comment by shimbaco** [comment]
あっすみません、コメントし損ねてました…。
そちらは内部用のフィールドで、公開の予定はありません。公開するとまずいかなと思い… 🙇
