### ISSUE TITLE
Annict API

### ISSUE THREAD

**Issue by shimbaco** [annict/annict#192]
- [x] GET /v1/works
- [x] GET /v1/episodes
- [x] POST /v1/me/statuses
- [x] GET /v1/records
- [x] POST /v1/me/records
- [x] PATCH /v1/me/records/:record_id
- [x] DELETE /v1/me/records/:record_id
- [x] GET /v1/me/works
- [x] GET /v1/me/programs
- [x] ページネーション周りをちゃんとする
- [x] records, statusesに `application_id` を登録する
- [x] /sign_in ページの見た目を整える
- [x] Doorkeeperが提供するページの見た目を整える
- [x] `oauth_applications` に `user_id` を格納する
- [x] `oauth_applications` が物理削除できないようにする
  - `records`, `statuses` に `oauth_application_id` があり、アプリケーション名などが利用され続けるため
- [x] アプリケーションを作った利用者が退会したとき、そのアプリケーションのトークンが利用できないようにする
- [x] タイムゾーン周りをちゃんとする
- [x] 認証済みアプリケーション一覧を設定ページに設ける
- [x] テストを書く
- [x] ----- とりあえず公開してみる #408 -----
- [x] Add `record_comments_count` to episodes
  - ref: https://twitter.com/_elzup_/status/823097959751434240
- [x] Add `filter_has_record_comment` to records
- [x] Add `status` to /v1/me/works
- [x] Add avatar_url and background_image_url to users
- [x] GET /v1/me
- [x] GET /v1/users
- [x] GET /v1/following
- [x] GET /v1/followers
- [x] GET /v1/me/following_activities
- [x] GET /v1/activities
- [x] ----- とりあえず公開してみる part.2 #716 -----
- [ ] Add rating to /v1/episodes
  - ref: https://twitter.com/tkhsh_yt/status/857656413836816384
- [ ] GET /v1/me/channels
- [ ] PUT /v1/me/channels/:channel_id
  - チャンネル登録
- [ ] DELETE /v1/me/channels/:channel_id
  - チャンネル削除
- [ ] GET /v1/me/channel_works
- [ ] PUT /v1/me/works/:work_id/channels/:channel_id
  - 作品ごとのチャンネル設定
- [ ] DELETE /v1/me/works/:work_id/channels/:channel_id
  - 作品ごとのチャンネル削除
- [ ] POST /v1/me/following/:(user_id|username)
  - フォロー
- [ ] DELETE /v1/me/following/:(user_id|username)
  - アンフォロー
- [ ] GET /v1/me/notifications
- [ ] GET /v1/statuses
- [ ] GET /v1/programs
- [ ] GET /v1/people
- [ ] GET /v1/organizations
- [ ] GET /v1/casts
- [ ] GET /v1/staffs
- [ ] POST /v1/records/:record_id/likes
- [ ] DELETE /v1/records/:record_id/likes/:like_id
- [ ] POST /v1/statuses/:status_id/likes
- [ ] DELETE /v1/statuses/:status_id/likes/:like_id

**Comment by elzup** [comment]
WEB のepisode ページ、感想一覧のようにコメントがあるもののみを取得したいと思っています。
GET /v1/records について filter_has_comment みたいなパラメータがあるとページングが少なくすむので欲しいです><

**Comment by shimbaco** [comment]
@elzup 確かにコメント付きの記録だけに絞りこめると便利そうですね。追加します！フィードバックありがとうございます！🙏

**Comment by touyu** [comment]
Get /v1/me/works で work の status(wanna_watch ...etc) が取得できるようにして欲しいです!

**Comment by shimbaco** [comment]
@touyu そう言えば今、自分が設定している作品のステータスが取得できないですね…！ありがとうございます、追加します！

**Comment by shimbaco** [comment]
We'll head to GraphQL so I'll close this issue...!
