### ISSUE TITLE
/v1/me/programs でepisodesが空になる。

### ISSUE THREAD

**Issue by ehu-151** [annict/annict#2091]
放送時刻を取得しようと思い、/v1/me/programs にリクエストしたところ、空のepisodesが帰ってきたのでisuueを書かせていただきます。

対象
https://annict.wikihub.io/wiki/api/me-programs

現象
episodesが空になる

https://api.annict.com/v1/me/programs?filter_work_ids=6446&access_token=????
```
{"programs":[],"total_count":0,"next_page":2,"prev_page":null}
```
page=2
```
{"programs":[],"total_count":0,"next_page":3,"prev_page":1}
```
page=3
```
{"programs":[],"total_count":0,"next_page":4,"prev_page":2}
```

**Comment by shimbaco** [comment]
すみません、スルーしちゃってました。
`/v1/me/programs` にリクエストを送ったとき `episode` フィールドが空になることがある (ちゃんとepisodeが参照できるときもある) ということですよね？
放送予定だけ登録されていてエピソードが登録されていないときにそのようなレスポンスになることがあると思います。

それとWikiHubのドキュメントは古い可能性があるので、 docs.annict.com のほうを参照いただければと思います。 🙇 
https://docs.annict.com/ja/api/v1/me-programs.html

**Comment by ehu-151** [comment]
ご返信ありがとうございます！ちょっと確認遅れましたが...すみません。

>/v1/me/programs にリクエストを送ったとき episode フィールドが空になることがある (ちゃんとepisodeが参照できるときもある) ということですよね？

説明が足りず誤解を招きました。申し訳ございません。実際は「episodeが参照できるときもある」は確認が取れていません。つまり、レスポンスで`"programs": []`しか見たことがありません。例えば、

https://docs.annict.com/ja/api/v1/me-programs.html に例として書かれているリクエストは空で帰ってきます。(tokenは https://annict.com/settings/apps で作成しました。scopeはreadです)

パラメータ：`sort_started_at`, `filter_started_at_gt`

https://api.annict.com/v1/me/programs?sort_started_at=desc&filter_started_at_gt=2016/05/05%2002:00&access_token=

```
{
    "programs": [],
    "total_count": 0,
    "next_page": 2,
    "prev_page": null
}
```

パラメータ：`filter_started_at_gt`

https://api.annict.com/v1/me/programs?filter_started_at_gt=2016/05/05%2002:00&access_token=

```
{
    "programs": [],
    "total_count": 0,
    "next_page": 2,
    "prev_page": null
}
```

パラメータ：なし

https://api.annict.com/v1/me/programs?access_token=

```
{
    "programs": [],
    "total_count": 0,
    "next_page": 2,
    "prev_page": null
}
```

パラメータ：`filter_work_ids`(作品IDで絞り込み, [`/v1/works`](https://docs.annict.com/ja/api/v1/works.html)の例の作品IDを使用)

https://api.annict.com/v1/me/programs?filter_work_ids=4168&access_token=

```
{
    "programs": [],
    "total_count": 0,
    "next_page": 2,
    "prev_page": null
}
```

パラメータ：filter_ids(値は[`/v1/me/programs`](https://docs.annict.com/ja/api/v1/me-programs.html)の例から参照)

https://api.annict.com/v1/me/programs?filter_ids=35387&access_token=

```
{
    "programs": [],
    "total_count": 0,
    "next_page": 2,
    "prev_page": null
}
```

パラメータ：`filter_channel_ids`(値は[`/v1/me/programs`](https://docs.annict.com/ja/api/v1/me-programs.html)の例から参照)

https://api.annict.com/v1/me/programs?filter_channel_ids=4&access_token=G6yBHmQU8ABQHAtDAzgsFWvLOwFPj6zUTDempEe8Vuc

```
{
    "programs": [],
    "total_count": 0,
    "next_page": 2,
    "prev_page": null
}
```

また、質問なのですが`/v1/me/programs`はエンドポイント？に`me`があるので、個人のアカウントに紐づいているのでしょうか？だとしたら、空なのはtokenの持ち主のannictアカウントで、何かAction(ここでいう、postで何かを登録やannictのwebページで何か操作)をする必要があるのでしょうか？

**Comment by shimbaco** [comment]
> また、質問なのですが/v1/me/programsはエンドポイント？にmeがあるので、個人のアカウントに紐づいているのでしょうか？

はい、そうです。ドキュメントの文書が分かりづらいですね。。[放送予定ページ](https://annict.jp/programs)で見られるデータと同じようなデータを取得することができます。
`"programs": []` となっているということは、仰るとおりアクセストークンを発行したユーザが作品のステータスを「見てる」または「見たい」にしておらず、放送予定ページに表示される番組情報が存在しないからかと思います。

**Comment by ehu-151** [comment]
取得できました！単純なミスが原因でした。申し訳ございません。🙇
原因は「[放送予定ページ](https://annict.jp/channels)でチャンネルを登録してなかったこと」です。

Issue対応ありがとうございました。
