### ISSUE TITLE
「チェックイン」→「記録」

### ISSUE THREAD

**Issue by shimbaco** [annict/annict#224]
「チェックイン」という「事前に何かをする」というニュアンスが含まれた言葉を使用している影響で、「アニメを見る前に記録するべきなのか、それとも見た後に記録するべきなのか？」という話をよく目にします。なので名称変更しようかと思います。

* 名詞: チェックイン (checkin) -> 記録 (record)
* 動詞: チェックインする (checkin) -> 記録する (record)

現状Twitterにシェアしたときには「○○にチェックイン！」などと本文に含まれますが、これも「○○を見ました」という少し落ち着いたトーンの文言に変更しようかと思います。

## 公開後タスク

* [x] [トップページのスクショを差し替える](https://github.com/annict/annict/pull/227#discussion_r37657151)
* [x] tipsテーブルの「エピソードにチェックインしよう」を「見たエピソードを記録しよう」に変更する

**Comment by shimbaco** [comment]
@kunitoo 本番環境に反映しました。ご対応ありがとうございました! :smile:

**Comment by kunitoo** [comment]
本番環境への反映ありがとうございます！
