### ISSUE TITLE
作品一覧ページに自分のフォローしてるユーザのアイコンを表示してほしい

### ISSUE THREAD

**Issue by bakorer** [annict/annict#374]
![pasted_image_2_19_16__22_11](https://cloud.githubusercontent.com/assets/844012/13176462/d268e0a2-d755-11e5-8242-e6707ddde25f.png)

**Comment by bakorer** [comment]
@shimbaco よろです。

**Comment by shimbaco** [comment]
@bakorer わざわざスクショまでw ありがとうございます! 優先度調整して対応しますw

**Comment by shimbaco** [comment]
done! です!

Annict Blog — 作品一覧ページで、その作品をチェックしている友達が見られるようになりました
http://blog.annict.com/post/139666772203/work-friends
