### ISSUE TITLE
モバイルで閲覧時、一部のページで不要な横スクロールが生じる

### ISSUE THREAD

**Issue by be-path** [annict/annict#3894]
モバイルで閲覧時、ライブラリページの横幅が画面幅よりわずかに広く、数ピクセル分の横スクロールが生じます。ブラウザが横スクロールバーの領域を確保するためか、画面下部のツールバー（？）も含めた縦スクロールも生じてツールバーのボタン類が押しにくくなってしまいます。

![Screenshot_20230129-180712](https://user-images.githubusercontent.com/3887644/215316372-20355bc4-b2f2-4909-a664-9754e1540bca.png)

モバイル版 Chrome 109 で確認しています。ライブラリページの他、プロフィールページとそこからたどった記録ページでも同様の現象が見られました。

**Comment by shimbaco** [comment]
確認したところ小さめの端末を使ってるとこうなるみたいですね。
起票ありがとうございます、対応しますー

**Comment by shimbaco** [comment]
こちら遅くなりましたが対応しました 🙏

**Comment by be-path** [comment]
ありがとうございます！こちらの環境 (Pixel 6) で表示確認しました。完璧です🥰

**Comment by be-path** [comment]
すみません。見逃していました……。プロフィールページで問題が解消していないようです。

https://annict.com/@nal

Close したあとにすみません🙇

**Comment by shimbaco** [comment]
ご確認ありがとうございます。対応漏れでした！
遅くなりましたが修正しました 🙏

**Comment by be-path** [comment]
ありがとうございます😭
