### ISSUE TITLE
Cannot login via Twitter since last week.

### ISSUE THREAD

**Issue by jcaosola** [annict/annict#3941]
This problem continues existing from last week.
any plan to fix this?
![image](https://github.com/annict/annict/assets/7110993/0219275b-cd87-493d-8323-bbf7df39d6f9)

**Comment by shimbaco** [comment]
We used old Twitter app in Annict and it looks like it has been discontinued.
So we deleted the sign in with Twitter feature. Please login with email instead of Twitter. 🙏
https://annict.com/forum/posts/1708 (Japanese announcement)

**Comment by jcaosola** [comment]
If I create a new account, how to take over my old account, which login via twitter?

**Comment by jcaosola** [comment]
never mind, I use the my email to find back my account, thanks!
