### ISSUE TITLE
PVを5件以上登録している場合の「全て見る」のリンクが機能しない

### ISSUE THREAD

**Issue by sue445** [annict/annict#3949]
作品にPVを5件以上登録している場合にスクショのように「全て見る」のリンクが出ていますが、このリンクのリンク先が `#` になっていて機能していないようです。

![image](https://github.com/annict/annict/assets/608755/a717beab-9713-4f97-95c9-580c80c499fe)

不具合は下記の作品で確認していますが、おそらく他の作品でもリンクが死んでいる予感です。

* https://annict.com/works/10567 
* https://annict.com/works/4612

**Comment by carlospazuzu** [comment]
![image](https://github.com/annict/annict/assets/6942685/9dfa4d60-d7f7-49b7-8276-9f59b82b4b19)

確かに、このリンクのコードは完全ではありません。ビデオセクションにリダイレクトすることで修正できると思います。私がやってもいいですか？

**Comment by shimbaco** [comment]
すみません反応遅くなりました 🙏 
フィードバックありがとうございます。リンク先ずっとちゃんと書いてなかったんですね… 😇 

@carlospazuzu 
ぜひお願いします！ 🙏

**Comment by carlospazuzu** [comment]
Couldn't send a PR because maybe I've got no permission.

![image](https://github.com/annict/annict/assets/6942685/7f48969e-8f08-475f-a1e9-d5f7bbc75874)

Am I mistaken or I should be in the contributors list?
