### ISSUE TITLE
icalの形式が一部不正である

### ISSUE THREAD

**Issue by onokatio** [annict/annict#4019]
annictが出力するical(webcal)の形式が厳密には規格に沿っておらず、一部クライアント、特にAppleカレンダー等で購読エラーが発生します。

https://icalendar.org/validator.html?url=https://annict.com/@onokatio/ics

複数ありますが、主な原因は改行コードとmime typeのようです。

**Comment by shimbaco** [comment]
こちら遅くなりましたが対応しました 🙏 

Googleカレンダー以外のカレンダーでも放送情報が表示できるようになりました - Forum | Annict https://annict.com/forum/posts/1834
