### ISSUE TITLE
開発用の初期のseedsデータをアプリを起動できるものにして欲しい

### ISSUE THREAD

**Issue by bells17** [annict/annict#442]
https://github.com/annict/annict#annictを動かす に従ってサーバーを起動して
[http://localhost:3000/](http://localhost:3000/) にアクセスすると以下のエラーになってしまう

<img width="1416" alt="nomethoderror_at__" src="https://cloud.githubusercontent.com/assets/2158863/15436611/d35918e8-1efd-11e6-84a6-eec6b9ef2284.png">

原因としては `seeds.rb` で生成されるデータの内 `works` ~ `items` が入っていないことが原因のようです。

```
annict_development=> SELECT COUNT(*) FROM works;
 count
-------
     0
(1 row)
```

恐らく `works` に紐づく `number_formats` のデータが存在しないことが原因だと思います。

```
Foreign-key constraints:
    "fk_rails_41b1e89600" FOREIGN KEY (number_format_id) REFERENCES number_formats(id)
    "fk_rails_762950ee4f" FOREIGN KEY (season_id) REFERENCES seasons(id)
```

よろしくお願いします。

**Comment by shimbaco** [comment]
@bells17 早速のコントリビュートありがとうございます!! そしてお手数をおかけしてすみません…。
普段本番環境のデータを使って開発しているので、ついseedデータを疎かにしてしまうんですよね…。なんとかします! 🙇

**Comment by shimbaco** [comment]
本番環境のデータに入っている外部に公開しちゃいけない系データを適当な値にするサーバを用意して、そこからデータを取得するようにすれば良さそう。

**Comment by bells17** [comment]
すみません。よろしくお願いします！！

**Comment by shimbaco** [comment]
「本番環境のデータに入っている外部に公開しちゃいけない系データを適当な値にするサーバを用意して、そこからデータを取得するようにすれば良さそう。」と思ってたんですが、公開しちゃいけないデータをうっかり公開しちゃう気がしたので、普通に `seeds.rb` を修正しました!
現在はエラーにならないかと思います! 🙇
