### ISSUE TITLE
[API] How to get image of each item?

### ISSUE THREAD

**Issue by hotchemi** [annict/annict#449]
Thank you for your great service 😄 
Are there any way to get a cover image of each item via current API? annict.imgix.net?

**Comment by shimbaco** [comment]
@hotchemi  Thank you for your feedback!

Unfortunately, you can't get cover images from current API. Truthfully, we want to provide with them. But we decided to not include cover images in API to consider copyright.
Currently, our web page is displaying cover images based on [Amazon's associates program](https://affiliate.amazon.co.jp/gp/associates/agreement). But our API can't apply this. So we can't provide cover images via API.

We apologize for not be satisfied your expectation. すみません…! 🙇

**Comment by hotchemi** [comment]
>  copyright

Ah really make sense. It's so sensitive problem, undestood:)
