### ISSUE TITLE
動画サイトで公式配信されているアニメを探せる機能

### ISSUE THREAD

**Issue by bakorer** [annict/annict#451]
## 実現したいこと

動画サイトで公式配信されているを検索できる機能を実装して欲しいです ❗ 
## 目的・背景

朝起きたら、「Annict で dTV で配信されているアニメが検索できたら便利じゃん！」と思い issue 作成しました :octocat: 
## 対応期限

よしなに 💃 
## ゴール
- [ ] リリースノートを書く
- [ ] @bakorer に mention ください 👍 
## KPI

dアニメストアで配信されているアニメが Annict 上で絞り込めるようにしたい。

**Comment by shimbaco** [comment]
ご要望ありがとうございます! よしなに対応します!

**Comment by bakorer** [comment]
機能追加、ありがとうございました！
