### ISSUE TITLE
質問 : AnnictAPIのOAuth認証について

### ISSUE THREAD

**Issue by konifar** [annict/annict#461]
すごく初歩的な質問で申し訳ないのですが、AndroidアプリでOAuth認証する時の流れを確認させてください。

ログイン/登録ボタンを押したらログイン画面のあとにこの画面が表示されて
![___annict](https://cloud.githubusercontent.com/assets/1269214/15817020/ddc2b288-2c10-11e6-89cf-14f731677697.png)

そのあとこの画面で認証コードをユーザーがコピーして
![___annict](https://cloud.githubusercontent.com/assets/1269214/15817037/eceb0fa8-2c10-11e6-8b5c-01d0fe228aab.png)

Androidの画面に戻って貼り付けてもらって、認証コードを元にトークンを取得するみたいな流れで合ってますか？

ユーザーにコピペしてもらう以外にシームレスに認証させるやり方があれば教えてほしいです 🙇

**Comment by shimbaco** [comment]
@konifar ご質問ありがとうございます! 僕もネイティブアプリでOAuth認証 (というかアプリ開発自体…) の経験はないので、よくわかっていません…! ＞＜
WebViewでAnnictの認証ページを開いて、「認証コード」のページまで行ったときにDOMを操作してコードを取得する、といったことはできたりするのでしょうか? もしDOMの操作が可能であればそんな感じで行けるかな? と思いました。
もし他のサービスでOAuth認証をされたご経験があれば、そのときサービス側がどういったフローを提供していたか教えて頂けるとありがたいです! OAuthで認証してもらう機能を提供したのも今回が初めてなので…! :joy:

**Comment by konifar** [comment]
@shimbaco 回答ありがとうございます！redirect_urlを指定するやり方など、いくつかやり方ありそうなので試してみますね。
もう一点確認なのですがredirect_urlは、例えば `android://annict` のようなカスタムスキーマをつけたURLだとバリデーションに引っかかってエラーになってしまったりしますか？

**Comment by shimbaco** [comment]
@konifar 

> もう一点確認なのですがredirect_urlは、例えば android://annict のようなカスタムスキーマをつけたURLだとバリデーションに引っかかってエラーになってしまったりしますか？

バリデーションエラーにはなりません! 今後もバリデーションを設ける予定はありません。 😃

**Comment by konifar** [comment]
@shimbaco ありがとうございます！じゃあなんとかなりそうなので色々試してみます 💪 
このIssueはクローズしていただいて大丈夫です！
