### ISSUE TITLE
クロスオリジンのエラー

### ISSUE THREAD

**Issue by nukosuke** [annict/annict#467]
[annict.js](https://github.com/nukosuke/annict.js)というAnnictのJavaScriptクライアントライブラリを作成しているものです。

Node.js向けに作り始めたものですが、ブラウザもサポートすることにしまして単一ファイルにパッケージングしたのですがCross Originのエラーが出てしまいデータが取得できません。

https://github.com/nukosuke/annict.js/pull/25#issuecomment-226527111

そこで`Access-Control-Allow-Origin`ヘッダをAPIのレスポンスに含めていただきたいのですが可能でしょうか？

**Comment by shimbaco** [comment]
@nukosuke ご報告ありがとうございます! そういえばCORSの設定してなかったですね…。対応しますので、今しばらくお待ち下さい!

**Comment by shimbaco** [comment]
@nukosuke 対応しました! `Access-Control-Allow-Origin` などが付加されるようになったかと思います!

**Comment by nukosuke** [comment]
@shimbaco さん

ご対応ありがとうございます！
ただ、認証系の `/oauth/*`に関しても有効性の確認やログアウト処理などで

- /oauth/token/info
- /oauth/revoke

の上記２つのエンドポイントにアクセスしたいのですがこちらもご対応いただけないでしょうか:bow: 🙇

**Comment by nukosuke** [comment]
`/v1/*` に関してはこちらでも取得できることを確認しました！

**Comment by shimbaco** [comment]
@nukosuke ご確認ありがとうございます!

> ただ、認証系の /oauth/*に関しても有効性の確認やログアウト処理などで
> /oauth/token/info
> /oauth/revoke
> の上記２つのエンドポイントにアクセスしたい

なるほど! そちらも対応したほうが良さそうですね。ということで対応しました! 今は `/oauth` 以下もいけると思います!

**Comment by nukosuke** [comment]
@shimbaco さん

アクセスできました！🎉🎉🎉
ありがとうございます！！:bow: 🙇 🙇

**Comment by shimbaco** [comment]
良かったです!! 😆
