### ISSUE TITLE
WindowsのChromeでステータス変更のセレクトボックスがちゃんと表示されない

### ISSUE THREAD

**Issue by shimbaco** [annict/annict#495]
ご意見1: https://twitter.com/prince__0203/status/758565324534849537
ご意見2: https://twitter.com/pump_pump_king/status/758567745688514560

WindowsのChromeでこうなってしまうっぽい。

**Comment by kunitoo** [comment]
Linux のChromeでも同様の現象が起こります。
以下のバージョンで現象を確認してます。

- Version 50.0.2661.102 (64-bit)

**Comment by shimbaco** [comment]
@kunitoo おお…Mac以外全滅だったんですね…。ありがとうございます、併せて修正します。 🙇

**Comment by shimbaco** [comment]
とりあえず https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ から仮想マシンをダウンロード中。重い…。

**Comment by shimbaco** [comment]
@kunitoo 修正しました! Windowsでしか確認できていませんが、LinuxのChromeも直ったかと思います。m(__)m

![virtualbox_ie11 - win8 1_02_08_2016_23_47_40](https://cloud.githubusercontent.com/assets/56767/17356354/d350e022-590b-11e6-8e8f-aba463263412.png)

**Comment by kunitoo** [comment]
@shimbaco 反応遅くなりましたが、Linux でも直ってました :smile: ありがとうございます。
