### ISSUE TITLE
ItemのURL文字列の長さのvalidationの変更の提案

### ISSUE THREAD

**Issue by chikyukotei** [annict/annict#504]
いつもAnnictを快適に利用させて頂いています。
Amazonの商品URLには長いフォーマットと短いフォーマットが存在し、長いフォーマットの場合作品の画像登録時にAmazonのURLが500文字を超過してしまう場合があります。
**劇場版NARUTO -ナルト- ブラッド・プリズン**の例を挙げると

* [長いフォーマット](https://www.amazon.co.jp/%E5%8A%87%E5%A0%B4%E7%89%88NARUTO-%E3%83%8A%E3%83%AB%E3%83%88--%E3%83%96%E3%83%A9%E3%83%83%E3%83%89%E3%83%BB%E3%83%97%E3%83%AA%E3%82%BA%E3%83%B3%E3%80%90%E5%AE%8C%E5%85%A8%E7%94%9F%E7%94%A3%E9%99%90%E5%AE%9A%E7%89%88%E3%80%91%EF%BC%8810%E5%88%86%E9%96%93%E4%BB%A5%E4%B8%8A%E3%81%AE%E6%9C%AA%E5%85%AC%E9%96%8B%E6%98%A0%E5%83%8F%E4%BB%98%E3%81%8D%EF%BC%89-DVD-%E7%AB%B9%E5%86%85%E9%A0%86%E5%AD%90/dp/B006KVV976/ref=sr_1_fkmr0_1?ie=UTF8&qid=1471229668&sr=8-1-fkmr0&keywords=%E5%8A%87%E5%A0%B4%E7%89%88NARUTO+-%E3%83%8A%E3%83%AB%E3%83%88-+%E3%83%96%E3%83%A9%E3%83%83%E3%83%89%E3%83%BB%E3%83%97%E3%83%AA%E3%82%BA%E3%83%B3) - 641文字
* [短いフォーマット](https://www.amazon.co.jp/dp/B006KVV976/ref=sr_1_fkmr0_1?ie=UTF8&qid=1471229668&sr=8-1-fkmr0&keywords=%E5%8A%87%E5%A0%B4%E7%89%88NARUTO+-%E3%83%8A%E3%83%AB%E3%83%88-+%E3%83%96%E3%83%A9%E3%83%83%E3%83%89%E3%83%BB%E3%83%97%E3%83%AA%E3%82%BA%E3%83%B3) - 246文字

となり、長いフォーマットの場合500文字を超過します。
短いフォーマットであれば500文字を超えることは無いので登録できないということはないですが、
誰でも登録しやすくすることを考えたら文字列の長さの制限を緩めたほうがよいかと思います。

コードの変更については[`app/models/concerns/item_common.rb`](https://github.com/annict/annict/blob/eb464fc874fdf54526fa6831852d5a542ab0815e/app/models/concerns/item_common.rb)を一行修正すればよいのではないかと思います。

**Comment by shimbaco** [comment]
@chikyukotei ご報告ありがとうございます! 商品名が長いとそういうことが起きますね…。文字数制限の緩和をしました。
ただ商品によってはまだ制限に引っかかる可能性があるので、 #505 にてISBN/ASINコードのみを入力するように改修しようかと思います。 🙇 

こちらのIssueは一旦Closeさせて頂きます。何かありましたらReopenをお願いします!
