### ISSUE TITLE
1度記録した番組を削除しても放送予定に復活しない

### ISSUE THREAD

**Issue by ckoshien** [annict/annict#549]
例として今期の「レガリア」ですが、再放送の放送予定を見るために
初回放送の記録(4話まで)を削除しましたが、放送予定に掲載されません。
1度でも記録してしまったものは削除しても内部的にレコードが残ってしまうのでしょうか？

**Comment by shimbaco** [comment]
@ckoshien 放送ページに出すか出さないかは記録とは別の箇所で判断しています。。具体的にはLatestStatusモデルの `watched_episode_ids` になります。
ステータスを「見た」または「中止」に変更すると `watched_episode_ids` が空になるようになっているので、また放送ページに表示されるようになるかと思います。
