### ISSUE TITLE
Display stats graph on work detail page

### ISSUE THREAD

**Issue by shimbaco** [annict/annict#599]
**Graph libraries:**

- http://plottablejs.org/
- https://gionkunz.github.io/chartist-js/
- http://www.chartjs.org/

**Comment by shimbaco** [comment]
From Anilist:

https://anilist.co/anime/21460/HibikeEuphonium2

![anilist hibike euphonium 2 - anime 2017-03-06 23-54-37](https://cloud.githubusercontent.com/assets/56767/23615009/595e04c2-02c8-11e7-8335-2df2a1656d32.jpg)

**Comment by wopian** [comment]
chartjs also has a vue wrapper: http://vue-chartjs.org/#/

**Comment by shimbaco** [comment]
Thank you for the information! :blush:
