### ISSUE TITLE
近未来Annict -格好良く・効率の良いページへ-

### ISSUE THREAD

**Issue by Kifads** [annict/annict#629]
[「Annictより回答を頂きました」](http://nitizakki.tk/annict-answer-2016-12/)に記述したが伝わらなかったデザインの話。一番最後に書いた「サイドバー無いならいっそ動かせばいいんじゃない？」の事です。

僕の思っているイメージは google AdSenseの新しくなったホームページのように一部分のみ表示が変わる(serverからファイルを持ってくる)ようにデザインを作る。※PCでの話です
例えば現在の今期アニメ一覧ページの中で「anime」という作品があったとする。

> anime　を選択
> その部分のフレーム（コンテンツ）だけ左側に _x_ px移動
> 右側の空いたスペースに作品情報を表示　←ここで記録が可能
> 他のアニメを選択したい場合、左側に移動したフレームより選択できる。

メリット　：一時的に選択できる情報が増えるが普段は少なくて済む
デメリット：作業が大変

言葉で伝えにくい内容ではありますが、恐らく大変な作業になりますね....(汗)

要約；つまり他には真似出来ないデザインと効率性を手に入れたい。
伝わりますか...?

**Comment by shimbaco** [comment]
ご要望ありがとうございます！
うーん、何となくわかりましたが、見た目に関する話でしたら、できればスクショなどで具体的な例を出して頂けると、理解や修正の助けになってありがたいです。
右側に表示されるコンテンツ内容がイメージできないのと、保守が難しそうという印象なので、対応はしないかと思います。すみません。
一覧ページからサッと作品情報が確認できるデザインは良さそうなので、今後頂いたアイデアに似た機能を追加するかもしれません。 🙇
