### ISSUE TITLE
API POST oauth/token で translation missing

### ISSUE THREAD

**Issue by elzup** [annict/annict#652]
POST oauth/token にて code に期限切れの code などを指定すると translate のエラーが出ていました。
サーバーサイドの エラーが出ていました。
(重要度は低いかもしれませんが報告です。)

```
curl -F client_id=xxxx \
-F client_secret=xxxx \
-F grant_type=authorization_code \
-F redirect_uri=urn:ietf:wg:oauth:2.0:oob \
-F code=[invalid code] \
-X POST https://api.annict.com/oauth/token

{"error":"invalid_grant","error_description":"translation missing: ja.doorkeeper.errors.messages.invalid_grant"}
```

**Comment by shimbaco** [comment]
@elzup ご連絡ありがとうございます！これは恥ずかしい…。修正します！ 🙇

**Comment by shimbaco** [comment]
doorkeeper.ja.yml を置いたので、リニューアル版をリリースしたあとはもう発生しないかと思います。
https://github.com/annict/annict/blob/e8b5406fe9b908fd5db4c8f559d75af310e001f1/config/locales/doorkeeper.ja.yml#L95
日本語訳はまた後日に…！
