### ISSUE TITLE
Language switcher displays languages in current locale

### ISSUE THREAD

**Issue by wopian** [annict/annict#691]
The language switcher in the footer displays the language names in the current locale. So when viewing the site in Japanese, English is 英語. Vice versa with Japanese when viewing in English.

![](http://i.imgur.com/LQluG6i.png)
![](http://i.imgur.com/Lah9G8R.png)

The switcher should ideally use the native name of the language, as currently it is expecting the user to know what their language is called in another language.

![](http://i.imgur.com/xZEHDee.png)
![](http://i.imgur.com/OWjkEB6.png)

**Comment by shimbaco** [comment]
@wopian Good point! (Why I couldn't notice this... 😅 )
I'll fix it! Thank you for letting me know!

**Comment by shimbaco** [comment]
![annict 2017-02-12 03-28-29](https://cloud.githubusercontent.com/assets/56767/22856369/588f8c48-f0d3-11e6-9e12-e006d65ce6a9.jpg)

@wopian Fixed! Thank you for your report!
