### ISSUE TITLE
新シーズン通知

### ISSUE THREAD

**Issue by elzup** [annict/annict#704]
# Why
友人の意見からなのですが。
「観たアニメのリストアップ」というケースのユーザ(私も昔これでした)だと、
「シーズンが切り替わるタイミングで Annict をチェックしたいけど忘れてしまう」ことがある。

# What
* シーズンごとに、あるタイミングでメール通知する
* 登録時に機能説明
* 発展: そういうユーザの検知して、機能のおすすめする。

**Comment by shimbaco** [comment]
@elzup ご要望ありがとうございます！
#213 で通知メールのもろもろを実装しようと思っているので、そのタイミングで一緒にできると良さそうですね。通知のタイミングは、わりと来期アニメのデータが登録されたあと放送開始前までに、という感じになるかなと思います。

**Comment by shimbaco** [comment]
今期アニメから送り始めました！何かありましたらReopenして教えて頂ければ幸いです。 🙇 
[Annict Blog — 四半期の始めに新アニメのお知らせメールを送り始めました](http://blog.annict.com/post/159101163303/seasonal-anime-notification)
