### ISSUE TITLE
modify status name

### ISSUE THREAD

**Issue by luccafort** [annict/annict#706]
annictでは以下の5つのステータスで管理をしていると思います。

- 見てる
- 見たい
- 見た
- 中断
- 中止

みてる系のステータスは問題ないのですが
中断と中止がパッとみどういう状態を表しているのかがわかりにくいように思います。

[Annictについて](https://annict.com/about)も見ましたが
特にステータスの詳細がかかれていないため、当初？？？となってしまいました。

私の認識が間違っていなければ、中断は一時的に見ることをやめる、中止は見ることをやめた…だと思っています。
ですので以下の文言に変更する、Annictについてに各ステータスの説明を書くなどの検討をいただければなあと思います。

中断 → 一時中断
中止 → 閲覧中止

PRを作っておくろうかとも考えたのですがなにか考えがあってそうしているのかな？とも思ったのでissueに上げさせてもらいました。
すでに似たような提案があればクローズしちゃってください。

あと新デザイン、めっちゃ見やすくなってありがたいです！ 🙇

**Comment by shimbaco** [comment]
@luccafort ご提案ありがとうございます！
この話は結構色々な方から伺います。やはり分かりづらいですかね…。
5つのステータスを横一列に並べたとき、文字数が多いと一列に収まらないケースがあったので、できるだけ短い単語にしたいという背景がありました。ただ見せ方を少し変えればなんとかなりそうな気もしますね。ちょっと考えてみます！

**Comment by shimbaco** [comment]
@luccafort 対応がものすごく遅くなりましたが、文言を変更しました！
[ステータスの「中断」と「中止」がそれぞれ「一時中断」「視聴中止」になりました \- Forum \| Annict](https://annict.jp/forum/posts/117)

見ていたものが映像なので、「閲覧」よりは「視聴」かなと思い、「閲覧中止」ではなく「視聴中止」とさせて頂いています。

フィードバックありがとうございました！このIssueはCloseします。何かありましたらReopenをお願いします。 🙇
