### ISSUE TITLE
『埋め込みタグ』を出力

### ISSUE THREAD

**Issue by Kifads** [annict/annict#714]
annictはSNSという位置づけらしいので、どうしても拡張配信したい...
ブログなどでオススメのアニメを紹介する時に「はてブ」のリンクカードのような形、スタイルで

- タイトル(エピソード名)
- 総合評価(個別評価)
- 作品イメージ画像

を出力できるようにする。
(サーバー負荷対策のために、評価は取得時点のものにしたほうがいいかもしれない...)

**Comment by shimbaco** [comment]
@Kifads ご要望 (と呼ぶには文書が断定的で釈然としませんが…) ありがとうございます！
#464 のようなステータス変更を行うための埋め込みタグの実装はいつかやりたいなと思っていますが、このIssueにあるようなことをする予定は今のところありません。作品画像はAmazonアソシエイトの規約上、Annictのサイト上でだけ使えるということになっているので、仮にやることになっても画像は表示できません。
「[Annict Widgets](https://github.com/nukosuke/annict-widgets)」のように、APIを利用して同じようなことはできそうですね。

ということでこちらは閉じさせていただきます。 🙇
