### ISSUE TITLE
非ログイン状態で /oauth/authorize してログイン後のリダイレクト先

### ISSUE THREAD

**Issue by elzup** [annict/annict#725]
非ログインユーザが api 認証ページを開いたとき、ログイン後にトップではなく認証ページにリダイレクトしてほしいです。

annict api を使ったスマホアプリだと、ユーザがスマホで annict.com にログインしていない場合も考えられます。
現状だと App → ブラウザ(ログイン、トップ) → App → ブラウザ(認証ページ、コード) と手間なので出来れば解決してほしいです。

**Comment by shimbaco** [comment]
@elzup ご要望ありがとうございます！ログイン後にリダイレクトするページがうまく保存できていないみたいですね…。修正します！

**Comment by shimbaco** [comment]
@elzup 確認したところ、 `annict.com/oauth/authorize?client_id=(クライアントID)&response_type=code&redirect_uri=(リダイレクトURI)&scope=read` のURLにAnnictにログインしていない状態でアクセスし、ログインすると認証ページに遷移したので問題ないように見えたのですが、そちらの環境だとログイン後トップページにリダイレクトしてしまうのでしょうか？

![untitled](https://cloud.githubusercontent.com/assets/56767/23613232/eabeeadc-02c1-11e7-99af-f86accde9046.gif)

**Comment by elzup** [comment]
すいません💦
annict.com/oauth/〜 でなく api.annict.com/oauth/〜 に飛ばしていました！
スマホでもPCでも正常に動作しいるの確認しました

**Comment by shimbaco** [comment]
@elzup なるほど！api.annict.comのほうだったんですね。確かにこちらだとトップページに飛ばされますね…。
認証時にサイトにアクセスするときはどちらのドメインでも良いのですが、どちらかと言うとelzupさんが試されたとおり `api.annict.com` のほうが良さそうなので、先ほど修正しました！
現在は `api.annict.com` でも認証ページに遷移するかと思います。 🙇
