### ISSUE TITLE
[layout bug] "current season" label is messed up with mobile browser

### ISSUE THREAD

**Issue by hotchemi** [annict/annict#735]
When user open annict from mobile devices, bottom bar's "current season" label is messed up as figure below.
I didn't come up with a fix way, presumably the most convenient way is changing title like "works" or shorter one...? 🤔 
 
<img width="250" alt="screen shot 2017-03-13 at 0 20 40" src="https://cloud.githubusercontent.com/assets/471318/23833025/22dbff0c-0783-11e7-87a2-b286e709372a.png">

**Comment by shimbaco** [comment]
@hotchemi Thank you for letting me know! I fixed the word into "Airing"! 😃 

![annict 2017-03-13 23-27-41](https://cloud.githubusercontent.com/assets/56767/23858709/b02f4816-0844-11e7-94f9-968ff0d96e6c.jpg)

Please let me know if there are any issues!

**Comment by hotchemi** [comment]
@shimbaco Thx for your quick fix! that's perfect 😀
