### ISSUE TITLE
視聴済みの話数が放送予定に復活する

### ISSUE THREAD

**Issue by ckoshien** [annict/annict#743]
一度3/20に発生している不具合ですが、昨夜から再び現象が再発しています。
slack上では一度解決したように見えたのですが、
修正前のソースをコミットされていないでしょうか？

**Comment by shimbaco** [comment]
ご連絡ありがとうございます！この前の修正では不十分だったようです。
再度修正してみました。もしまた再発しましたら、お手数ですがこのIssueをReopenしてご連絡頂ければ幸いです。 🙇
