### ISSUE TITLE
シリーズ作品登録画面でのソート

### ISSUE THREAD

**Issue by ckoshien** [annict/annict#759]
現状、シリーズ作品画面ではID順に表示されていますが、
シリーズでは時系列に並べた方がよいと思います。
他の編集画面同様、「ソート番号」のカラムをDBに足していただくか、
SQL発行時に時系列順にソートするなどできないでしょうか。

**Comment by shimbaco** [comment]
@ckoshien ご要望ありがとうございます！確かにそのほうが自然ですね。対応します。 💪
