### ISSUE TITLE
wrong link to API

### ISSUE THREAD

**Issue by pchw** [annict/annict#790]
![image](https://cloud.githubusercontent.com/assets/1183484/26749571/cf67c0a2-4848-11e7-9535-1be0836bc8f8.png)

`Annict API` link to https://docs.annict.com/ja/api/

https://docs.annict.com/ja/api/
![image](https://cloud.githubusercontent.com/assets/1183484/26749574/de63de24-4848-11e7-82d2-84aa4e74cdd4.png)

it should link to https://docs.annict.com/ja/ ?

**Comment by shimbaco** [comment]
@pchw Oops, thank you for letting me know! Fixed!
