### ISSUE TITLE
Translation missing is displayed on confirmation flash message

### ISSUE THREAD

**Issue by y0za** [annict/annict#816]
## 問題点
メールアドレスの確認用に送られてくるメールに記載されたリンクを開いたときに、表示されるフラッシュメッセージの内容が`translation missing`となります。

↓開発環境を作って再現させた結果
![annict_confirmation_flash](https://user-images.githubusercontent.com/16757772/28317734-278032b4-6c03-11e7-86f0-a0b337c7e8dd.png)

## 原因
[confirmations_controller](https://github.com/annict/annict/blob/master/app/controllers/confirmations_controller.rb#L6)で`confirmations.confirmed`をキーとしてi18nを参照しているのですが、対応する値が`config/locales`内に存在しないみたいです。

**Comment by shimbaco** [comment]
@y0za ご報告ありがとうございます！修正しました！😃
