### ISSUE TITLE
Fate/kaleid liner プリズマ☆イリヤのクロをお気に入りキャラクター登録していたら，劇場版「SERVAMP-サーヴァンプ-」-Alice in the Garden-の別のキャラのクロのオススメメールが来てしまった

### ISSUE THREAD

**Issue by pchw** [annict/annict#858]
https://annict.jp/characters/1051

![image](https://user-images.githubusercontent.com/1183484/32923537-70101bf2-cb7b-11e7-9d07-2d8a72549289.png)

**Comment by will-meaning** [comment]
@pchw ご連絡ありがとうございます。

こちらは『劇場版「SERVAMP-サーヴァンプ-」-Alice in the Garden-』のキャスト情報をAnnict DBに登録しようとした時に、本来であれば【SERVAMP-サーヴァンプ-】シリーズのクロが登録されるところで、【Fate/kaleid liner プリズマ☆イリヤ】シリーズのクロが登録された状態になってしまい、またそのことに気がつけず、そのままにしてしまったため、オススメメールが届いてしまったようです。

お手数おかけしてすみませんが、現在はキャスト情報のDBは、正しい状態に修正済みとなります。

**Comment by pchw** [comment]
ご対応ありがとうございます！

**Comment by shimbaco** [comment]
ご連絡&ご対応ありがとうございました！ 🙏
