### ISSUE TITLE
AndroidのChromeでAnnictを閲覧した際にアイコンが表示されない

### ISSUE THREAD

**Issue by will-meaning** [annict/annict#863]
特定の画面というよりも、すべての画面のすべてのアイコンで事象を確認しております。
また、念のため、Chromeのキャッシュもクリアしましたが、回復せずといった状況です。

### 閲覧環境
* Android 5.1.1
* Chrome 62.0.3202.84

### 参考画像
![image](https://user-images.githubusercontent.com/16857034/33267979-b6672b4a-d3be-11e7-82e9-2d7ded9b1cdd.png)

**Comment by shimbaco** [comment]
@will-meaning ご連絡ありがとうございます！
フォントがうまくダウンロードできていないみたいですね。少し設定を変えてみたのですが、今も同じ状況でしょうか？

**Comment by will-meaning** [comment]
@shimbaco ご対応ありがとうございます！！
ちゃんと表示されるようになりました ☺️ :+1:

**Comment by shimbaco** [comment]
@will-meaning ご確認ありがとうございました！良かったです！
