### ISSUE TITLE
ステータスの選択が未選択なのか選択済みなのかひと目で判断したい

### ISSUE THREAD

**Issue by mottox2** [annict/annict#881]
<img width="1128" alt="2018-01-08 19 04 23" src="https://user-images.githubusercontent.com/7007253/34666277-e0e3633a-f4a6-11e7-9018-9351bf8367e6.png">
バグではありませんが、アニメでステータスを選択していく時に未選択なのか選択済みなのかわかりづらいので見た目に差をつけられると嬉しいと思いました。

ミニマムとして 未選択なのか選択済みなのか が判断出来ると嬉しいです
optionalで視聴停止等が分かると…

**Comment by shimbaco** [comment]
ご要望ありがとうございます。ステータスを色で区別するという考えはありませんでした。
確かに色で区別できるとわかりやすそうですね。対応します。(が、他にやりたいことがあるのですぐには対応しないと思います。。)

**Comment by shimbaco** [comment]
@mottox2 対応しました！ステータスごとに色を変えると目がチカチカしそうだったので、一旦選択済/未選択の色だけ変えています。

![2018 annict 2018-03-04 05-30-06](https://user-images.githubusercontent.com/56767/36938986-41b9a7f0-1f6d-11e8-8675-b48093c563c7.png)
