### ISSUE TITLE
ステータス未選択の際に視聴記録をつけると放送予定から消えない

### ISSUE THREAD

**Issue by ckoshien** [annict/annict#890]
ステータス「選択してください」の状態で視聴記録をつけた際、
後からステータスを「見る」に変更すると放送予定では未視聴の扱いになっているようです。
想定としては記録時のステータスにかかわらず、視聴済みとして扱うべきなのでは…と思っていますが
いかがでしょうか？

**Comment by shimbaco** [comment]
フィードバックありがとうございます。
全話見終えたあと、もう一度1話を見てステータスを「見てる」にしたとき、どこから視聴済みとすべきか？などを考えると難しいんですよね。
トップページで「次のエピソード」をクリックして頂けるとありがたいです。放送予定ページでもエピソードをスキップできるようにする予定です。m(__)m

**Comment by ckoshien** [comment]
なるほど。再視聴の可能性は考えていませんでした。
そういう意味で仕様通りなのですね。
了解しました。

**Comment by ckoshien** [comment]
記録の際にステータスを一度確認するよう促すものがあってもいいですね。
仮に実装するとして、ポップアップはクリック数が増えるのでやめた方がよいですね。
・メリット
後から誤りに気付いてユーザがデータを修正しなくて済む(←私がそうです)
・デメリット
ステータスを気にしないユーザにとっては毎回うるさくなる
修正の工数

一応ご提案まで。

**Comment by shimbaco** [comment]
ありがとうございます。
個人的にはデメリットのほうが大きく感じるので、実装はしないと思います。m(__)m
