### ISSUE TITLE
like 関連の API が欲しい

### ISSUE THREAD

**Issue by elzup** [annict/annict#984]
作っているクライアントで使いたいのでリクエストします。(リクエストばかりで恐縮です)

* RecordObject から「viewer がそのレコードをお気に入りしているかどうか」が知りたいです。(record.viewerIsLike)
* お気に入り登録する Mutation が使いたいです。(likeRecord)

**Comment by shimbaco** [comment]
@elzup ご要望ありがとうございます！まだ考え中なのですが、Like機能をGitHubのように ❤️ や 👍 のような絵文字が送り合えるリアクション機能にしようかと思っています。リアクション機能に変えるならAPIはそのあとに追加したほうが二度手間にならないし良いかな…と思ってしばらく経っている状態です。
今は別のことをしているのでリアクション機能の着手まで時間がかかると思いますが、それまでお待ちいただけると幸いです。 🙇

**Comment by elzup** [comment]
なるほど了解です！
その機能はとても楽しみです！
